name: Deploy maboke243

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
       node-version: '16'
    
    - name: Init new repo in prod folder and commit files
      run: |
        cd  dist/
        cp index.html 404.html
        git init
        git add -A
        git config --local user.email "zcore243@gmail.com"
        git config --local user.name "zcorp"
        git commit -m 'deploy'
        
    - name: Force push to destination branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        branch: gui-prod #gui-prod
        force: true
        directory: ./dist